[package]
name = "nest"
version = "0.1.0"
edition = "2021"

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
simple_graphics = { git = "https://github.com/etnad101/simple-graphics-rs" }
egui = "0.27.2"
eframe = "0.27.0"