[package]
name = "nest"
version = "0.1.0"
edition = "2021"

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
egui = "0.31.1"
eframe = "0.31.1"
rfd = "0.15.3"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"